name: FT-Plugin
description: Fully Toasted Custom Plugin
version: 1.0
main: tech.elitebyte.ftp.FTP
author: elitebyte

commands:
  anvil:
    description: Rains Anvils
  fireball:
    description: Fireball towards
  explode:
    description: Fake explode
