name: FT-Plugin
description: Fully Toasted Custom Plugin!
version: 1.0
main: tech.elitebyte.ftp.FTP
author: elitebyte

commands:
  wanderer:
    description: Runs the wanderer rank perk.
  bloodletter:
    description: Runs the bloodletter rank perk.
  explode:
    description: Fake explode
  apprentice:
    description: Runs the apprentice rank perk.
  mage:
    description: Runs the mage rank perk.
  magus:
    description: Runs the magus rank perk.
  acolyte:
    description: Runs the acolyte rank perk.
